In [23]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [24]:
iris = load_iris()
x = iris.data
y = iris.target

In [25]:
df = pd.DataFrame(iris.data)
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train,X_test, Y_train,Y_test = train_test_split(x,y,test_size = 0.3,random_state = 7)
X_train.shape, Y_train.shape
X_test.shape , Y_test.shape

((45, 4), (45,))

In [29]:
from sklearn.naive_bayes import GaussianNB
model =GaussianNB()

In [32]:
model.fit(X_train,Y_train)
X_train.shape, X_test.shape

((105, 4), (45, 4))

In [33]:
pred = model.predict(X_test)
pred

array([2, 1, 0, 1, 1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 0, 2, 2, 2, 0, 0, 1, 2,
       1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 0, 2, 1, 0, 0, 0, 0, 2, 2, 1, 2, 2,
       1])

In [34]:
from sklearn.metrics import classification_report 

print(classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.87      0.81      0.84        16
          2       0.83      0.88      0.86        17

avg / total       0.89      0.89      0.89        45



In [38]:
data = pd.DataFrame({'actual':list(Y_test), 'pred':pred})
data.head()

actual  pred
0       2     2
1       1     1
2       0     0
3       1     1
4       2     1

In [36]:
score =  model.score(X_test,Y_test)
print(score)

0.8888888888888888


In [37]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,pred)
print(matrix)

[[12  0  0]
 [ 0 13  3]
 [ 0  2 15]]


In [43]:
from sklearn.naive_bayes import MultinomialNB
model1 =MultinomialNB()

In [44]:
model1.fit(X_train,Y_train)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [47]:
pred1 = model1.predict(X_test)
pred1

array([2, 1, 0, 1, 2, 0, 1, 1, 0, 1, 1, 1, 0, 2, 0, 1, 2, 2, 0, 0, 1, 2,
       1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 0, 2, 1, 0, 0, 0, 0, 2, 2, 1, 2, 2,
       1])

In [48]:
from sklearn.metrics import classification_report 

print(classification_report(Y_test,pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.94      1.00      0.97        16
          2       1.00      0.94      0.97        17

avg / total       0.98      0.98      0.98        45



In [49]:
data1 = pd.DataFrame({'actual':list(Y_test), 'pred':pred1})
data1.head()

actual  pred
0       2     2
1       1     1
2       0     0
3       1     1
4       2     2

In [50]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,pred)
print(matrix)

[[12  0  0]
 [ 0 13  3]
 [ 0  2 15]]
