In [100]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits

In [116]:
digit = load_digits()
x = digit.data
y = digit.target

In [102]:
df = pd.DataFrame(digit.data)
df.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
X_train,X_test, Y_train,Y_test = train_test_split(x,y,test_size = 0.25,random_state = 7)
X_train.shape, Y_train.shape
X_test.shape , Y_test.shape

((450, 64), (450,))

In [105]:
df = pd.DataFrame(digit.data)
df.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [106]:
df1 = (df-df.min())/(df.max()-df.min())
df1.head()


0    1       2       3       4       5    6    7    8    9  ...       54  \
0 NaN  0.0  0.3125  0.8125  0.5625  0.0625  0.0  0.0  0.0  0.0 ...   0.0000   
1 NaN  0.0  0.0000  0.7500  0.8125  0.3125  0.0  0.0  0.0  0.0 ...   0.0000   
2 NaN  0.0  0.0000  0.2500  0.9375  0.7500  0.0  0.0  0.0  0.0 ...   0.3125   
3 NaN  0.0  0.4375  0.9375  0.8125  0.0625  0.0  0.0  0.0  0.5 ...   0.5625   
4 NaN  0.0  0.0000  0.0625  0.6875  0.0000  0.0  0.0  0.0  0.0 ...   0.0000   

    55   56   57      58      59      60      61      62   63  
0  0.0  0.0  0.0  0.3750  0.8125  0.6250  0.0000  0.0000  0.0  
1  0.0  0.0  0.0  0.0000  0.6875  1.0000  0.6250  0.0000  0.0  
2  0.0  0.0  0.0  0.0000  0.1875  0.6875  1.0000  0.5625  0.0  
3  0.0  0.0  0.0  0.4375  0.8125  0.8125  0.5625  0.0000  0.0  
4  0.0  0.0  0.0  0.0000  0.1250  1.0000  0.2500  0.0000  0.0  

[5 rows x 64 columns]

In [107]:
from sklearn.preprocessing import StandardScaler
x_std = StandardScaler().fit_transform(X_train, Y_train)

In [108]:
from sklearn.decomposition import PCA
model = PCA(n_components = 2)
model.fit(x_std)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [109]:
from sklearn.linear_model import LogisticRegression

In [110]:
logisticRegr = LogisticRegression()
logisticRegr.fit(x_std, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [111]:
pred = logisticRegr.predict(X_test)
pred

array([6, 0, 5, 9, 2, 9, 0, 1, 1, 0, 1, 8, 2, 5, 2, 8, 1, 8, 9, 1, 0, 8,
       0, 4, 5, 3, 1, 0, 0, 4, 1, 4, 9, 4, 6, 1, 4, 0, 6, 6, 0, 9, 3, 6,
       6, 2, 0, 1, 9, 6, 2, 8, 1, 9, 0, 2, 0, 8, 4, 6, 8, 5, 8, 7, 8, 7,
       7, 6, 1, 4, 5, 5, 6, 6, 2, 0, 1, 8, 7, 5, 8, 2, 4, 1, 2, 8, 8, 8,
       8, 7, 6, 8, 8, 5, 6, 2, 1, 0, 1, 1, 4, 1, 9, 3, 1, 6, 9, 0, 3, 8,
       6, 9, 3, 8, 0, 1, 3, 8, 8, 6, 3, 7, 3, 9, 0, 8, 0, 9, 1, 8, 2, 2,
       3, 6, 9, 4, 0, 5, 4, 2, 9, 1, 0, 8, 5, 0, 2, 2, 7, 4, 8, 9, 8, 8,
       6, 0, 4, 4, 1, 5, 0, 2, 4, 1, 8, 2, 3, 7, 2, 9, 1, 3, 5, 9, 1, 6,
       8, 7, 5, 8, 0, 8, 2, 1, 3, 3, 6, 0, 2, 8, 4, 1, 1, 7, 5, 7, 6, 6,
       8, 1, 0, 6, 8, 7, 8, 1, 9, 8, 5, 9, 3, 6, 8, 1, 2, 0, 7, 5, 3, 0,
       8, 2, 0, 6, 0, 9, 8, 8, 1, 7, 9, 8, 3, 6, 2, 8, 1, 5, 9, 2, 9, 9,
       8, 8, 1, 6, 7, 8, 7, 5, 7, 8, 9, 5, 7, 8, 3, 8, 8, 8, 2, 8, 9, 5,
       8, 2, 8, 0, 1, 8, 1, 0, 8, 9, 1, 7, 1, 1, 7, 7, 1, 8, 8, 8, 4, 3,
       5, 9, 4, 1, 8, 1, 8, 7, 2, 3, 1, 1, 1, 0, 2,

In [112]:
from sklearn import metrics
metrics.accuracy_score(Y_test,pred)


0.8377777777777777

In [115]:
from sklearn.metrics import classification_report 
print(classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.94      0.97        52
          1       0.68      0.88      0.76        48
          2       1.00      0.83      0.91        48
          3       1.00      0.74      0.85        43
          4       1.00      0.51      0.68        47
          5       1.00      0.87      0.93        38
          6       0.92      0.95      0.94        38
          7       1.00      0.85      0.92        41
          8       0.53      0.94      0.68        50
          9       0.83      0.87      0.85        45

avg / total       0.89      0.84      0.84       450



In [114]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,pred)
print(matrix)


[[49  2  0  0  0  0  0  0  1  0]
 [ 0 42  0  0  0  0  0  0  5  1]
 [ 0  0 40  0  0  0  0  0  7  1]
 [ 0  1  0 32  0  0  0  0  9  1]
 [ 0 11  0  0 24  0  3  0  7  2]
 [ 0  0  0  0  0 33  0  0  3  2]
 [ 0  1  0  0  0  0 36  0  1  0]
 [ 0  0  0  0  0  0  0 35  5  1]
 [ 0  3  0  0  0  0  0  0 47  0]
 [ 0  2  0  0  0  0  0  0  4 39]]
